flags: {}
packages:
- '.'
# - location:
#     git: https://github.com/simonmichael/hledger.git
#     commit: 282e85c6028227938457fb3b94eb333c4ba4ae65
#   subdirs:
#   - hledger-lib
#   extra-dep: true

resolver: lts-8.18
pvp-bounds: both
