# enter the containig dir and run with 'buchhaltung -p . import barclaycardus.csv barclaycardus'
users:
  - name: nick
    ledgers:
      mainLedger:      nick/ledger.ledger
      imported:        nick/import.ledger
      addedByThisUser: nick/entered_by_nick.ledger
      addedByOthers:   nick/entered_by_others.ledger
    accountPrefixOthers: Accounts receivable:Friends
    ignoredAccountsOnAdd:
      - "Transfer"
      - "Cash"
    bankAccounts:
      PNC Bank:
        checking: "Assets:Checking:PNC"
      Barclays Bank Delaware:
        1234: "Liabilities:Credit Cards:Barclaycard"
    aqBanking:
      configDir: nick/aqbanking
      connections: []
